name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/setup-pages@v2
      - name: Deploy to GitHub Pages
        run: |
          mkdir .github
          touch .github/index.html
          echo '<h1>GitHub Pages is working!</h1>' > .github/index.html
        shell: bash
